public class Control_Monad {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object whenM = (java.util.function.Function<Object, Object>) (dictMonad_0) -> ((new java.util.function.Supplier<Object>() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0).get("Applicative0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return (java.util.function.Function<Object, Object>) (mb_2) -> (java.util.function.Function<Object, Object>) (m_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0).get("Bind1"))).apply(null /* TODO: PrimUndefined */)).get("bind"))).apply(mb_2))).apply((java.util.function.Function<Object, Object>) (b_4) -> ( ((Boolean) (b_4)) ? m_3 : ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("pure"))).apply(Data_Unit.unit))); } })).get();
public static final Object unlessM = (java.util.function.Function<Object, Object>) (dictMonad_0) -> ((new java.util.function.Supplier<Object>() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0).get("Applicative0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return (java.util.function.Function<Object, Object>) (mb_2) -> (java.util.function.Function<Object, Object>) (m_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0).get("Bind1"))).apply(null /* TODO: PrimUndefined */)).get("bind"))).apply(mb_2))).apply((java.util.function.Function<Object, Object>) (b_4) -> ( ((Boolean) (null /* TODO: Op1 */)) ? m_3 : ( ((Boolean) (b_4)) ? ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("pure"))).apply(Data_Unit.unit) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); } })).get();
public static final Object monadProxy = new java.util.LinkedHashMap<String, Object>() {{ put("Applicative0", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Control_Applicative.applicativeProxy); put("Bind1", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Control_Bind.bindProxy); }};
public static final Object monadFn = new java.util.LinkedHashMap<String, Object>() {{ put("Applicative0", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Control_Applicative.applicativeFn); put("Bind1", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Control_Bind.bindFn); }};
public static final Object monadArray = new java.util.LinkedHashMap<String, Object>() {{ put("Applicative0", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Control_Applicative.applicativeArray); put("Bind1", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Control_Bind.bindArray); }};
public static final Object liftM1 = (java.util.function.Function<Object, Object>) (dictMonad_0) -> (java.util.function.Function<Object, Object>) (f_1) -> (java.util.function.Function<Object, Object>) (a_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0).get("Bind1"))).apply(null /* TODO: PrimUndefined */)).get("bind"))).apply(a_2))).apply((java.util.function.Function<Object, Object>) (a_prime_3) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0).get("Applicative0"))).apply(null /* TODO: PrimUndefined */)).get("pure"))).apply(((java.util.function.Function<Object, Object>) (f_1)).apply(a_prime_3)));
public static final Object ap = (java.util.function.Function<Object, Object>) (dictMonad_0) -> ((new java.util.function.Supplier<Object>() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0).get("Bind1"))).apply(null /* TODO: PrimUndefined */); public Object get() { return (java.util.function.Function<Object, Object>) (f_2) -> (java.util.function.Function<Object, Object>) (a_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("bind"))).apply(f_2))).apply((java.util.function.Function<Object, Object>) (f_prime_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("bind"))).apply(a_3))).apply((java.util.function.Function<Object, Object>) (a_prime_5) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0).get("Applicative0"))).apply(null /* TODO: PrimUndefined */)).get("pure"))).apply(((java.util.function.Function<Object, Object>) (f_prime_4)).apply(a_prime_5)))); } })).get();
}
