public class Control_Biapply {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object identity1 = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object identity2 = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object biapplyTuple = new java.util.LinkedHashMap<String, Object>() {{ put("biapply", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> new Data_Tuple.Tuple(((java.util.function.Function<Object, Object>) ((((Data_Tuple.Tuple) v_0).value0))).apply((((Data_Tuple.Tuple) v1_1).value0)), ((java.util.function.Function<Object, Object>) ((((Data_Tuple.Tuple) v_0).value1))).apply((((Data_Tuple.Tuple) v1_1).value1)))); put("Bifunctor0", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Data_Bifunctor.bifunctorTuple); }};
public static final Object biapply = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("biapply");
public static final Object biapplyFirst = (java.util.function.Function<Object, Object>) (dictBiapply_0) -> (java.util.function.Function<Object, Object>) (a_1) -> (java.util.function.Function<Object, Object>) (b_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapply_0).get("biapply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapply_0).get("Bifunctor0"))).apply(null /* TODO: PrimUndefined */)).get("bimap"))).apply((java.util.function.Function<Object, Object>) (v_3) -> Control_Biapply.identity1))).apply((java.util.function.Function<Object, Object>) (v_3) -> Control_Biapply.identity2))).apply(a_1)))).apply(b_2);
public static final Object biapplySecond = (java.util.function.Function<Object, Object>) (dictBiapply_0) -> (java.util.function.Function<Object, Object>) (a_1) -> (java.util.function.Function<Object, Object>) (b_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapply_0).get("biapply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapply_0).get("Bifunctor0"))).apply(null /* TODO: PrimUndefined */)).get("bimap"))).apply(Data_Function.$const))).apply(Data_Function.$const))).apply(a_1)))).apply(b_2);
public static final Object bilift2 = (java.util.function.Function<Object, Object>) (dictBiapply_0) -> (java.util.function.Function<Object, Object>) (f_1) -> (java.util.function.Function<Object, Object>) (g_2) -> (java.util.function.Function<Object, Object>) (a_3) -> (java.util.function.Function<Object, Object>) (b_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapply_0).get("biapply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapply_0).get("Bifunctor0"))).apply(null /* TODO: PrimUndefined */)).get("bimap"))).apply(f_1))).apply(g_2))).apply(a_3)))).apply(b_4);
public static final Object bilift3 = (java.util.function.Function<Object, Object>) (dictBiapply_0) -> (java.util.function.Function<Object, Object>) (f_1) -> (java.util.function.Function<Object, Object>) (g_2) -> (java.util.function.Function<Object, Object>) (a_3) -> (java.util.function.Function<Object, Object>) (b_4) -> (java.util.function.Function<Object, Object>) (c_5) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapply_0).get("biapply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapply_0).get("biapply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapply_0).get("Bifunctor0"))).apply(null /* TODO: PrimUndefined */)).get("bimap"))).apply(f_1))).apply(g_2))).apply(a_3)))).apply(b_4)))).apply(c_5);
}
