public class Control_Applicative {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object pure = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("pure");
public static final Object unless = (java.util.function.Function<Object, Object>) (dictApplicative_0) -> (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ( ((Boolean) (null /* TODO: Op1 */)) ? v1_2 : ( ((Boolean) (v_1)) ? ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApplicative_0).get("pure"))).apply(Data_Unit.unit) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()));
public static final Object when = (java.util.function.Function<Object, Object>) (dictApplicative_0) -> (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ( ((Boolean) (v_1)) ? v1_2 : ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApplicative_0).get("pure"))).apply(Data_Unit.unit));
public static final Object liftA1 = (java.util.function.Function<Object, Object>) (dictApplicative_0) -> (java.util.function.Function<Object, Object>) (f_1) -> (java.util.function.Function<Object, Object>) (a_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApplicative_0).get("Apply0"))).apply(null /* TODO: PrimUndefined */)).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApplicative_0).get("pure"))).apply(f_1)))).apply(a_2);
public static final Object applicativeProxy = new java.util.LinkedHashMap<String, Object>() {{ put("pure", (java.util.function.Function<Object, Object>) (v_0) -> new Type_Proxy.Proxy()); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Control_Apply.applyProxy); }};
public static final Object applicativeFn = new java.util.LinkedHashMap<String, Object>() {{ put("pure", (java.util.function.Function<Object, Object>) (x_0) -> (java.util.function.Function<Object, Object>) (v_1) -> x_0); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Control_Apply.applyFn); }};
public static final Object applicativeArray = new java.util.LinkedHashMap<String, Object>() {{ put("pure", (java.util.function.Function<Object, Object>) (x_0) -> null /* TODO: other literals */); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Control_Apply.applyArray); }};
}
