public class Control_Apply {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };
    public static Object arrayApply = FFI_STUB;
    public static Object arrayApply(Object... args) { return null; }

public static final Object identity = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object applyProxy = new java.util.LinkedHashMap<String, Object>() {{ put("apply", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> new Type_Proxy.Proxy()); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Data_Functor.functorProxy); }};
public static final Object applyFn = new java.util.LinkedHashMap<String, Object>() {{ put("apply", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (g_1) -> (java.util.function.Function<Object, Object>) (x_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (f_0)).apply(x_2))).apply(((java.util.function.Function<Object, Object>) (g_1)).apply(x_2))); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Data_Functor.functorFn); }};
public static final Object applyArray = new java.util.LinkedHashMap<String, Object>() {{ put("apply", Control_Apply.arrayApply); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Data_Functor.functorArray); }};
public static final Object apply = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("apply");
public static final Object applyFirst = (java.util.function.Function<Object, Object>) (dictApply_0) -> (java.util.function.Function<Object, Object>) (a_1) -> (java.util.function.Function<Object, Object>) (b_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */)).get("map"))).apply(Data_Function.$const))).apply(a_1)))).apply(b_2);
public static final Object applySecond = (java.util.function.Function<Object, Object>) (dictApply_0) -> (java.util.function.Function<Object, Object>) (a_1) -> (java.util.function.Function<Object, Object>) (b_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */)).get("map"))).apply((java.util.function.Function<Object, Object>) (v_3) -> Control_Apply.identity))).apply(a_1)))).apply(b_2);
public static final Object lift2 = (java.util.function.Function<Object, Object>) (dictApply_0) -> (java.util.function.Function<Object, Object>) (f_1) -> (java.util.function.Function<Object, Object>) (a_2) -> (java.util.function.Function<Object, Object>) (b_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */)).get("map"))).apply(f_1))).apply(a_2)))).apply(b_3);
public static final Object lift3 = (java.util.function.Function<Object, Object>) (dictApply_0) -> (java.util.function.Function<Object, Object>) (f_1) -> (java.util.function.Function<Object, Object>) (a_2) -> (java.util.function.Function<Object, Object>) (b_3) -> (java.util.function.Function<Object, Object>) (c_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */)).get("map"))).apply(f_1))).apply(a_2)))).apply(b_3)))).apply(c_4);
public static final Object lift4 = (java.util.function.Function<Object, Object>) (dictApply_0) -> (java.util.function.Function<Object, Object>) (f_1) -> (java.util.function.Function<Object, Object>) (a_2) -> (java.util.function.Function<Object, Object>) (b_3) -> (java.util.function.Function<Object, Object>) (c_4) -> (java.util.function.Function<Object, Object>) (d_5) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */)).get("map"))).apply(f_1))).apply(a_2)))).apply(b_3)))).apply(c_4)))).apply(d_5);
public static final Object lift5 = (java.util.function.Function<Object, Object>) (dictApply_0) -> (java.util.function.Function<Object, Object>) (f_1) -> (java.util.function.Function<Object, Object>) (a_2) -> (java.util.function.Function<Object, Object>) (b_3) -> (java.util.function.Function<Object, Object>) (c_4) -> (java.util.function.Function<Object, Object>) (d_5) -> (java.util.function.Function<Object, Object>) (e_6) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */)).get("map"))).apply(f_1))).apply(a_2)))).apply(b_3)))).apply(c_4)))).apply(d_5)))).apply(e_6);
}
