public class Data_Unfoldable1 {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };
    public static Object unfoldr1ArrayImpl = FFI_STUB;
    public static Object unfoldr1ArrayImpl(Object... args) { return null; }

public static final Object fromJust = (java.util.function.Function<Object, Object>) (v_0) -> ( ((Boolean) ((v_0 instanceof Data_Maybe.Just))) ? (((Data_Maybe.Just) v_0).value0) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get());
public static final Object lessThanOrEq = ((new java.util.function.Supplier<Object>() { Object __local_var_0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordIntImpl)).apply(new Data_Ordering.LT()))).apply(new Data_Ordering.EQ()))).apply(new Data_Ordering.GT()); public Object get() { return (java.util.function.Function<Object, Object>) (a1_1) -> (java.util.function.Function<Object, Object>) (a2_2) -> ( ((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__local_var_0)).apply(a1_1))).apply(a2_2) instanceof Data_Ordering.GT))) ? false : true); } })).get();
public static final Object greaterThanOrEq = ((new java.util.function.Supplier<Object>() { Object __local_var_0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordIntImpl)).apply(new Data_Ordering.LT()))).apply(new Data_Ordering.EQ()))).apply(new Data_Ordering.GT()); public Object get() { return (java.util.function.Function<Object, Object>) (a1_1) -> (java.util.function.Function<Object, Object>) (a2_2) -> ( ((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__local_var_0)).apply(a1_1))).apply(a2_2) instanceof Data_Ordering.LT))) ? false : true); } })).get();
public static final Object greaterThan = ((new java.util.function.Supplier<Object>() { Object __local_var_0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordIntImpl)).apply(new Data_Ordering.LT()))).apply(new Data_Ordering.EQ()))).apply(new Data_Ordering.GT()); public Object get() { return (java.util.function.Function<Object, Object>) (a1_1) -> (java.util.function.Function<Object, Object>) (a2_2) -> ( ((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__local_var_0)).apply(a1_1))).apply(a2_2) instanceof Data_Ordering.GT))) ? true : false); } })).get();
public static final Object unfoldr1 = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("unfoldr1");
public static final Object unfoldable1Maybe = new java.util.LinkedHashMap<String, Object>() {{ put("unfoldr1", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (b_1) -> new Data_Maybe.Just((((Data_Tuple.Tuple) ((java.util.function.Function<Object, Object>) (f_0)).apply(b_1)).value0))); }};
public static final Object unfoldable1Array = new java.util.LinkedHashMap<String, Object>() {{ put("unfoldr1", ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Unfoldable1.unfoldr1ArrayImpl)).apply(Data_Maybe.isNothing))).apply(Data_Unfoldable1.fromJust))).apply(Data_Tuple.fst))).apply(Data_Tuple.snd)); }};
public static final Object replicate1 = (java.util.function.Function<Object, Object>) (dictUnfoldable1_0) -> (java.util.function.Function<Object, Object>) (n_1) -> (java.util.function.Function<Object, Object>) (v_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictUnfoldable1_0).get("unfoldr1"))).apply((java.util.function.Function<Object, Object>) (i_3) -> ( ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Unfoldable1.lessThanOrEq)).apply(i_3))).apply(0))) ? new Data_Tuple.Tuple(v_2, new Data_Maybe.Nothing()) : new Data_Tuple.Tuple(v_2, new Data_Maybe.Just((((Integer) (i_3)) - ((Integer) (1))))))))).apply((((Integer) (n_1)) - ((Integer) (1))));
public static final Object replicate1A = (java.util.function.Function<Object, Object>) (dictApply_0) -> (java.util.function.Function<Object, Object>) (dictUnfoldable1_1) -> (java.util.function.Function<Object, Object>) (dictTraversable1_2) -> ((new java.util.function.Supplier<Object>() { Object sequence1_3 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictTraversable1_2).get("sequence1"))).apply(dictApply_0); public Object get() { return (java.util.function.Function<Object, Object>) (n_4) -> (java.util.function.Function<Object, Object>) (m_5) -> ((java.util.function.Function<Object, Object>) (sequence1_3)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Unfoldable1.replicate1)).apply(dictUnfoldable1_1))).apply(n_4))).apply(m_5)); } })).get();
public static final Object singleton = (java.util.function.Function<Object, Object>) (dictUnfoldable1_0) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Unfoldable1.replicate1)).apply(dictUnfoldable1_0))).apply(1);
public static final Object range = (java.util.function.Function<Object, Object>) (dictUnfoldable1_0) -> (java.util.function.Function<Object, Object>) (start_1) -> (java.util.function.Function<Object, Object>) (end_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictUnfoldable1_0).get("unfoldr1"))).apply(((new java.util.function.Supplier<Object>() { Object __local_var_3 = ( ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Unfoldable1.greaterThanOrEq)).apply(end_2))).apply(start_1))) ? 1 : -1); public Object get() { return (java.util.function.Function<Object, Object>) (i_4) -> ((new java.util.function.Supplier<Object>() { Object i_prime_5 = (((Integer) (i_4)) + ((Integer) (__local_var_3))); public Object get() { return new Data_Tuple.Tuple(i_4, ( ((Boolean) ((((Integer) (i_4)) == ((Integer) (end_2))))) ? new Data_Maybe.Nothing() : new Data_Maybe.Just(i_prime_5))); } })).get(); } })).get()))).apply(start_1);
public static final Object iterateN = (java.util.function.Function<Object, Object>) (dictUnfoldable1_0) -> (java.util.function.Function<Object, Object>) (n_1) -> (java.util.function.Function<Object, Object>) (f_2) -> (java.util.function.Function<Object, Object>) (s_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictUnfoldable1_0).get("unfoldr1"))).apply((java.util.function.Function<Object, Object>) (v_4) -> new Data_Tuple.Tuple((((Data_Tuple.Tuple) v_4).value0), ( ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Unfoldable1.greaterThan)).apply((((Data_Tuple.Tuple) v_4).value1)))).apply(0))) ? new Data_Maybe.Just(new Data_Tuple.Tuple(((java.util.function.Function<Object, Object>) (f_2)).apply((((Data_Tuple.Tuple) v_4).value0)), (((Integer) ((((Data_Tuple.Tuple) v_4).value1))) - ((Integer) (1))))) : new Data_Maybe.Nothing()))))).apply(new Data_Tuple.Tuple(s_3, (((Integer) (n_1)) - ((Integer) (1)))));
}
