public class Data_Predicate {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object Predicate = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object newtypePredicate = new java.util.LinkedHashMap<String, Object>() {{ put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> null /* TODO: PrimUndefined */); }};
public static final Object heytingAlgebraPredicate = new java.util.LinkedHashMap<String, Object>() {{ put("ff", (java.util.function.Function<Object, Object>) (v_0) -> ((java.util.LinkedHashMap<String, Object>) Data_HeytingAlgebra.heytingAlgebraBoolean).get("ff")); put("tt", (java.util.function.Function<Object, Object>) (v_0) -> ((java.util.LinkedHashMap<String, Object>) Data_HeytingAlgebra.heytingAlgebraBoolean).get("tt")); put("implies", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (g_1) -> (java.util.function.Function<Object, Object>) (a_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Data_HeytingAlgebra.heytingAlgebraBoolean).get("disj"))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Data_HeytingAlgebra.heytingAlgebraBoolean).get("not"))).apply(((java.util.function.Function<Object, Object>) (f_0)).apply(a_2))))).apply(((java.util.function.Function<Object, Object>) (g_1)).apply(a_2))); put("conj", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (g_1) -> (java.util.function.Function<Object, Object>) (a_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Data_HeytingAlgebra.heytingAlgebraBoolean).get("conj"))).apply(((java.util.function.Function<Object, Object>) (f_0)).apply(a_2)))).apply(((java.util.function.Function<Object, Object>) (g_1)).apply(a_2))); put("disj", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (g_1) -> (java.util.function.Function<Object, Object>) (a_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Data_HeytingAlgebra.heytingAlgebraBoolean).get("disj"))).apply(((java.util.function.Function<Object, Object>) (f_0)).apply(a_2)))).apply(((java.util.function.Function<Object, Object>) (g_1)).apply(a_2))); put("not", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (a_1) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Data_HeytingAlgebra.heytingAlgebraBoolean).get("not"))).apply(((java.util.function.Function<Object, Object>) (f_0)).apply(a_1))); }};
public static final Object contravariantPredicate = new java.util.LinkedHashMap<String, Object>() {{ put("cmap", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (x_2) -> ((java.util.function.Function<Object, Object>) (v_1)).apply(((java.util.function.Function<Object, Object>) (f_0)).apply(x_2))); }};
public static final Object booleanAlgebraPredicate = ((java.util.function.Function<Object, Object>) (Data_BooleanAlgebra.booleanAlgebraFn)).apply(Data_BooleanAlgebra.booleanAlgebraBoolean);
}
