public class Data_Op {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object Op = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object semigroupoidOp = new java.util.LinkedHashMap<String, Object>() {{ put("compose", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> (java.util.function.Function<Object, Object>) (x_2) -> ((java.util.function.Function<Object, Object>) (v1_1)).apply(((java.util.function.Function<Object, Object>) (v_0)).apply(x_2))); }};
public static final Object semigroupOp = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (f_1) -> (java.util.function.Function<Object, Object>) (g_2) -> (java.util.function.Function<Object, Object>) (x_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroup_0).get("append"))).apply(((java.util.function.Function<Object, Object>) (f_1)).apply(x_3)))).apply(((java.util.function.Function<Object, Object>) (g_2)).apply(x_3))); }};
public static final Object newtypeOp = new java.util.LinkedHashMap<String, Object>() {{ put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> null /* TODO: PrimUndefined */); }};
public static final Object monoidOp = (java.util.function.Function<Object, Object>) (dictMonoid_0) -> ((new java.util.function.Supplier<Object>() { Object mempty1_1 = ((java.util.LinkedHashMap<String, Object>) dictMonoid_0).get("mempty"); public Object get() { return ((new java.util.function.Supplier<Object>() { Object semigroupFn_2 = ((new java.util.function.Supplier<Object>() { Object __local_var_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonoid_0).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (f_3) -> (java.util.function.Function<Object, Object>) (g_4) -> (java.util.function.Function<Object, Object>) (x_5) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_2).get("append"))).apply(((java.util.function.Function<Object, Object>) (f_3)).apply(x_5)))).apply(((java.util.function.Function<Object, Object>) (g_4)).apply(x_5))); }}; } })).get(); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("mempty", (java.util.function.Function<Object, Object>) (v_3) -> mempty1_1); put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar__unused_3) -> semigroupFn_2); }}; } })).get(); } })).get();
public static final Object contravariantOp = new java.util.LinkedHashMap<String, Object>() {{ put("cmap", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (x_2) -> ((java.util.function.Function<Object, Object>) (v_1)).apply(((java.util.function.Function<Object, Object>) (f_0)).apply(x_2))); }};
public static final Object categoryOp = new java.util.LinkedHashMap<String, Object>() {{ put("identity", (java.util.function.Function<Object, Object>) (x_0) -> x_0); put("Semigroupoid0", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Data_Op.semigroupoidOp); }};
}
