public class Data_Comparison {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object append = (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (g_1) -> (java.util.function.Function<Object, Object>) (x_2) -> ((new java.util.function.Supplier<Object>() { Object __local_var_3 = ((java.util.function.Function<Object, Object>) (f_0)).apply(x_2); public Object get() { return ((new java.util.function.Supplier<Object>() { Object __local_var_4 = ((java.util.function.Function<Object, Object>) (g_1)).apply(x_2); public Object get() { return (java.util.function.Function<Object, Object>) (x_5) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Data_Ordering.semigroupOrdering).get("append"))).apply(((java.util.function.Function<Object, Object>) (__local_var_3)).apply(x_5)))).apply(((java.util.function.Function<Object, Object>) (__local_var_4)).apply(x_5)); } })).get(); } })).get();
public static final Object Comparison = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object semigroupComparison = new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Comparison.append)).apply(v_0))).apply(v1_1)); }};
public static final Object newtypeComparison = new java.util.LinkedHashMap<String, Object>() {{ put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> null /* TODO: PrimUndefined */); }};
public static final Object monoidComparison = new java.util.LinkedHashMap<String, Object>() {{ put("mempty", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> new Data_Ordering.EQ()); put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Data_Comparison.semigroupComparison); }};
public static final Object defaultComparison = (java.util.function.Function<Object, Object>) (dictOrd_0) -> ((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare");
public static final Object contravariantComparison = new java.util.LinkedHashMap<String, Object>() {{ put("cmap", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (x_2) -> (java.util.function.Function<Object, Object>) (y_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (v_1)).apply(((java.util.function.Function<Object, Object>) (f_0)).apply(x_2)))).apply(((java.util.function.Function<Object, Object>) (f_0)).apply(y_3))); }};
}
