public class Data_DivisionRing {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object recip = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("recip");
public static final Object rightDiv = (java.util.function.Function<Object, Object>) (dictDivisionRing_0) -> (java.util.function.Function<Object, Object>) (a_1) -> (java.util.function.Function<Object, Object>) (b_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictDivisionRing_0).get("Ring0"))).apply(null /* TODO: PrimUndefined */)).get("Semiring0"))).apply(null /* TODO: PrimUndefined */)).get("mul"))).apply(a_1))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictDivisionRing_0).get("recip"))).apply(b_2));
public static final Object leftDiv = (java.util.function.Function<Object, Object>) (dictDivisionRing_0) -> (java.util.function.Function<Object, Object>) (a_1) -> (java.util.function.Function<Object, Object>) (b_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictDivisionRing_0).get("Ring0"))).apply(null /* TODO: PrimUndefined */)).get("Semiring0"))).apply(null /* TODO: PrimUndefined */)).get("mul"))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictDivisionRing_0).get("recip"))).apply(b_2)))).apply(a_1);
public static final Object divisionringNumber = new java.util.LinkedHashMap<String, Object>() {{ put("recip", (java.util.function.Function<Object, Object>) (x_0) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Data_EuclideanRing.euclideanRingNumber).get("div"))).apply(1.0))).apply(x_0)); put("Ring0", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("sub", Data_Ring.numSub); put("Semiring0", (java.util.function.Function<Object, Object>) (_dollar__unused_1) -> new java.util.LinkedHashMap<String, Object>() {{ put("add", Data_Semiring.numAdd); put("zero", 0.0); put("mul", Data_Semiring.numMul); put("one", 1.0); }}); }}); }};
}
