public class Data_Maybe_Last {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object Last = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object showLast = (java.util.function.Function<Object, Object>) (dictShow_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("show", (java.util.function.Function<Object, Object>) (v_1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Data_Semigroup.semigroupString).get("append"))).apply("(Last "))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Data_Semigroup.semigroupString).get("append"))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (Data_Maybe.showMaybe)).apply(dictShow_0)).get("show"))).apply(v_1)))).apply(")"))); }};
public static final Object semigroupLast = new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> ( ((Boolean) ((v1_1 instanceof Data_Maybe.Just))) ? v1_1 : ( ((Boolean) ((v1_1 instanceof Data_Maybe.Nothing))) ? v_0 : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); }};
public static final Object ordLast = (java.util.function.Function<Object, Object>) (dictOrd_0) -> ((new java.util.function.Supplier<Object>() { Object eqMaybe1_1 = ((new java.util.function.Supplier<Object>() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("Eq0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("eq", (java.util.function.Function<Object, Object>) (x_2) -> (java.util.function.Function<Object, Object>) (y_3) -> ( ((Boolean) ((x_2 instanceof Data_Maybe.Nothing))) ? ( ((Boolean) ((y_3 instanceof Data_Maybe.Nothing))) ? true : false) : ( ((Boolean) (null /* TODO: Op2 */)) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("eq"))).apply((((Data_Maybe.Just) x_2).value0)))).apply((((Data_Maybe.Just) y_3).value0)) : false))); }}; } })).get(); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("compare", (java.util.function.Function<Object, Object>) (x_2) -> (java.util.function.Function<Object, Object>) (y_3) -> ( ((Boolean) ((x_2 instanceof Data_Maybe.Nothing))) ? ( ((Boolean) ((y_3 instanceof Data_Maybe.Nothing))) ? new Data_Ordering.EQ() : new Data_Ordering.LT()) : ( ((Boolean) ((y_3 instanceof Data_Maybe.Nothing))) ? new Data_Ordering.GT() : ( ((Boolean) (null /* TODO: Op2 */)) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare"))).apply((((Data_Maybe.Just) x_2).value0)))).apply((((Data_Maybe.Just) y_3).value0)) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())))); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar__unused_2) -> eqMaybe1_1); }}; } })).get();
public static final Object ord1Last = Data_Maybe.ord1Maybe;
public static final Object newtypeLast = new java.util.LinkedHashMap<String, Object>() {{ put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> null /* TODO: PrimUndefined */); }};
public static final Object monoidLast = new java.util.LinkedHashMap<String, Object>() {{ put("mempty", new Data_Maybe.Nothing()); put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Data_Maybe_Last.semigroupLast); }};
public static final Object monadLast = Data_Maybe.monadMaybe;
public static final Object invariantLast = Data_Maybe.invariantMaybe;
public static final Object functorLast = Data_Maybe.functorMaybe;
public static final Object extendLast = Data_Maybe.extendMaybe;
public static final Object eqLast = (java.util.function.Function<Object, Object>) (dictEq_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("eq", (java.util.function.Function<Object, Object>) (x_1) -> (java.util.function.Function<Object, Object>) (y_2) -> ( ((Boolean) ((x_1 instanceof Data_Maybe.Nothing))) ? ( ((Boolean) ((y_2 instanceof Data_Maybe.Nothing))) ? true : false) : ( ((Boolean) (null /* TODO: Op2 */)) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictEq_0).get("eq"))).apply((((Data_Maybe.Just) x_1).value0)))).apply((((Data_Maybe.Just) y_2).value0)) : false))); }};
public static final Object eq1Last = Data_Maybe.eq1Maybe;
public static final Object boundedLast = (java.util.function.Function<Object, Object>) (dictBounded_0) -> ((java.util.function.Function<Object, Object>) (Data_Maybe.boundedMaybe)).apply(dictBounded_0);
public static final Object bindLast = Data_Maybe.bindMaybe;
public static final Object applyLast = Data_Maybe.applyMaybe;
public static final Object applicativeLast = Data_Maybe.applicativeMaybe;
public static final Object altLast = new java.util.LinkedHashMap<String, Object>() {{ put("alt", ((java.util.LinkedHashMap<String, Object>) Data_Maybe_Last.semigroupLast).get("append")); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Data_Maybe.functorMaybe); }};
public static final Object plusLast = new java.util.LinkedHashMap<String, Object>() {{ put("empty", ((java.util.LinkedHashMap<String, Object>) Data_Maybe_Last.monoidLast).get("mempty")); put("Alt0", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Data_Maybe_Last.altLast); }};
public static final Object alternativeLast = new java.util.LinkedHashMap<String, Object>() {{ put("Applicative0", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Data_Maybe.applicativeMaybe); put("Plus1", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Data_Maybe_Last.plusLast); }};
}
