public class Data_Array_ST_Iterator {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final class Iterator {
            public final Object value0;
            public final Object value1;
            public Iterator(Object value0, Object value1) {
                this.value0 = value0;
                this.value1 = value1;
            }
        }
public static final Object $void = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Control_Monad_ST_Internal.functorST).get("map"))).apply((java.util.function.Function<Object, Object>) (v_0) -> Data_Unit.unit);
public static final Object void1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Control_Monad_ST_Internal.functorST).get("map"))).apply((java.util.function.Function<Object, Object>) (v_0) -> Data_Unit.unit);
public static final Object Iterator = (java.util.function.Function<Object, Object>) (value0) -> (java.util.function.Function<Object, Object>) (value1) -> new Data_Array_ST_Iterator.Iterator(value0, value1);
public static final Object peek = (java.util.function.Function<Object, Object>) (v_0) -> ((new java.util.function.Supplier<Object>() { Object __local_var_1 = (((Data_Array_ST_Iterator.Iterator) v_0).value1); public Object get() { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Control_Monad_ST_Internal.bindST).get("bind"))).apply(null /* TODO: PrimEffect */))).apply((java.util.function.Function<Object, Object>) (i_2) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Control_Monad_ST_Internal.applicativeST).get("pure"))).apply(((java.util.function.Function<Object, Object>) ((((Data_Array_ST_Iterator.Iterator) v_0).value0))).apply(i_2))); } })).get();
public static final Object next = (java.util.function.Function<Object, Object>) (v_0) -> ((new java.util.function.Supplier<Object>() { Object __local_var_1 = (((Data_Array_ST_Iterator.Iterator) v_0).value1); public Object get() { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Control_Monad_ST_Internal.bindST).get("bind"))).apply(null /* TODO: PrimEffect */))).apply((java.util.function.Function<Object, Object>) (i_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Control_Monad_ST_Internal.bindST).get("bind"))).apply(((new java.util.function.Supplier<Object>() { Object __local_var_3 = null /* TODO: PrimEffect */; public Object get() { return null /* TODO: PrimEffect */; } })).get()))).apply((java.util.function.Function<Object, Object>) (_dollar__unused_3) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Control_Monad_ST_Internal.applicativeST).get("pure"))).apply(((java.util.function.Function<Object, Object>) ((((Data_Array_ST_Iterator.Iterator) v_0).value0))).apply(i_2)))); } })).get();
public static final Object pushWhile = (java.util.function.Function<Object, Object>) (p_0) -> (java.util.function.Function<Object, Object>) (iter_1) -> (java.util.function.Function<Object, Object>) (array_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Control_Monad_ST_Internal.bindST).get("bind"))).apply(null /* TODO: PrimEffect */))).apply((java.util.function.Function<Object, Object>) (go__break_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Monad_ST_Internal.$while)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Control_Monad_ST_Internal.functorST).get("map"))).apply(((java.util.LinkedHashMap<String, Object>) Data_HeytingAlgebra.heytingAlgebraBoolean).get("not")))).apply(null /* TODO: PrimEffect */)))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Control_Monad_ST_Internal.bindST).get("bind"))).apply(((java.util.function.Function<Object, Object>) (Data_Array_ST_Iterator.peek)).apply(iter_1)))).apply((java.util.function.Function<Object, Object>) (mx_4) -> ( ((Boolean) (null /* TODO: Op2 */)) ? ((new java.util.function.Supplier<Object>() { Object __local_var_5 = (((Data_Maybe.Just) mx_4).value0); public Object get() { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Control_Monad_ST_Internal.bindST).get("bind"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Array_ST.pushImpl)).apply(__local_var_5))).apply(array_2)))).apply((java.util.function.Function<Object, Object>) (_dollar__unused_6) -> ((java.util.function.Function<Object, Object>) (Data_Array_ST_Iterator.$void)).apply(((java.util.function.Function<Object, Object>) (Data_Array_ST_Iterator.next)).apply(iter_1))); } })).get() : ((java.util.function.Function<Object, Object>) (Data_Array_ST_Iterator.void1)).apply(null /* TODO: PrimEffect */)))));
public static final Object pushAll = ((java.util.function.Function<Object, Object>) (Data_Array_ST_Iterator.pushWhile)).apply((java.util.function.Function<Object, Object>) (v_0) -> true);
public static final Object iterator = (java.util.function.Function<Object, Object>) (f_0) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Control_Monad_ST_Internal.functorST).get("map"))).apply(((java.util.function.Function<Object, Object>) (Data_Array_ST_Iterator.Iterator)).apply(f_0)))).apply(null /* TODO: PrimEffect */);
public static final Object iterate = (java.util.function.Function<Object, Object>) (iter_0) -> (java.util.function.Function<Object, Object>) (f_1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Control_Monad_ST_Internal.bindST).get("bind"))).apply(null /* TODO: PrimEffect */))).apply((java.util.function.Function<Object, Object>) (go__break_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Monad_ST_Internal.$while)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Control_Monad_ST_Internal.functorST).get("map"))).apply(((java.util.LinkedHashMap<String, Object>) Data_HeytingAlgebra.heytingAlgebraBoolean).get("not")))).apply(null /* TODO: PrimEffect */)))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Control_Monad_ST_Internal.bindST).get("bind"))).apply(((java.util.function.Function<Object, Object>) (Data_Array_ST_Iterator.next)).apply(iter_0)))).apply((java.util.function.Function<Object, Object>) (mx_3) -> ( ((Boolean) ((mx_3 instanceof Data_Maybe.Just))) ? ((java.util.function.Function<Object, Object>) (f_1)).apply((((Data_Maybe.Just) mx_3).value0)) : ( ((Boolean) ((mx_3 instanceof Data_Maybe.Nothing))) ? ((java.util.function.Function<Object, Object>) (Data_Array_ST_Iterator.void1)).apply(null /* TODO: PrimEffect */) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())))));
public static final Object exhausted = ((new java.util.function.Supplier<Object>() { Object __local_var_0 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Control_Monad_ST_Internal.functorST).get("map"))).apply(Data_Maybe.isNothing); public Object get() { return (java.util.function.Function<Object, Object>) (x_1) -> ((java.util.function.Function<Object, Object>) (__local_var_0)).apply(((java.util.function.Function<Object, Object>) (Data_Array_ST_Iterator.peek)).apply(x_1)); } })).get();
}
