public class Data_CommutativeRing {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object commutativeRingUnit = new java.util.LinkedHashMap<String, Object>() {{ put("Ring0", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Data_Ring.ringUnit); }};
public static final Object commutativeRingRecordNil = new java.util.LinkedHashMap<String, Object>() {{ put("RingRecord0", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Data_Ring.ringRecordNil); }};
public static final Object commutativeRingRecordCons = (java.util.function.Function<Object, Object>) (dictIsSymbol_0) -> (java.util.function.Function<Object, Object>) (_dollar__unused_1) -> (java.util.function.Function<Object, Object>) (dictCommutativeRingRecord_2) -> ((new java.util.function.Supplier<Object>() { Object ringRecordCons1_3 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ring.ringRecordCons)).apply(dictIsSymbol_0))).apply(null /* TODO: PrimUndefined */))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictCommutativeRingRecord_2).get("RingRecord0"))).apply(null /* TODO: PrimUndefined */)); public Object get() { return (java.util.function.Function<Object, Object>) (dictCommutativeRing_4) -> ((new java.util.function.Supplier<Object>() { Object ringRecordCons2_5 = ((java.util.function.Function<Object, Object>) (ringRecordCons1_3)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictCommutativeRing_4).get("Ring0"))).apply(null /* TODO: PrimUndefined */)); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("RingRecord0", (java.util.function.Function<Object, Object>) (_dollar__unused_6) -> ringRecordCons2_5); }}; } })).get(); } })).get();
public static final Object commutativeRingRecord = (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> (java.util.function.Function<Object, Object>) (dictCommutativeRingRecord_1) -> ((new java.util.function.Supplier<Object>() { Object ringRecord1_2 = ((new java.util.function.Supplier<Object>() { Object __local_var_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictCommutativeRingRecord_1).get("RingRecord0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return ((new java.util.function.Supplier<Object>() { Object semiringRecord1_3 = ((new java.util.function.Supplier<Object>() { Object __local_var_3 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_2).get("SemiringRecord0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("add", ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_3).get("addRecord"))).apply(new Type_Proxy.Proxy())); put("mul", ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_3).get("mulRecord"))).apply(new Type_Proxy.Proxy())); put("one", ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_3).get("oneRecord"))).apply(new Type_Proxy.Proxy()))).apply(new Type_Proxy.Proxy())); put("zero", ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_3).get("zeroRecord"))).apply(new Type_Proxy.Proxy()))).apply(new Type_Proxy.Proxy())); }}; } })).get(); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("sub", ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_2).get("subRecord"))).apply(new Type_Proxy.Proxy())); put("Semiring0", (java.util.function.Function<Object, Object>) (_dollar__unused_4) -> semiringRecord1_3); }}; } })).get(); } })).get(); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("Ring0", (java.util.function.Function<Object, Object>) (_dollar__unused_3) -> ringRecord1_2); }}; } })).get();
public static final Object commutativeRingProxy = new java.util.LinkedHashMap<String, Object>() {{ put("Ring0", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Data_Ring.ringProxy); }};
public static final Object commutativeRingNumber = new java.util.LinkedHashMap<String, Object>() {{ put("Ring0", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("sub", Data_Ring.numSub); put("Semiring0", (java.util.function.Function<Object, Object>) (_dollar__unused_1) -> new java.util.LinkedHashMap<String, Object>() {{ put("add", Data_Semiring.numAdd); put("zero", 0.0); put("mul", Data_Semiring.numMul); put("one", 1.0); }}); }}); }};
public static final Object commutativeRingInt = new java.util.LinkedHashMap<String, Object>() {{ put("Ring0", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("sub", Data_Ring.intSub); put("Semiring0", (java.util.function.Function<Object, Object>) (_dollar__unused_1) -> new java.util.LinkedHashMap<String, Object>() {{ put("add", Data_Semiring.intAdd); put("zero", 0); put("mul", Data_Semiring.intMul); put("one", 1); }}); }}); }};
public static final Object commutativeRingFn = (java.util.function.Function<Object, Object>) (dictCommutativeRing_0) -> ((new java.util.function.Supplier<Object>() { Object ringFn_1 = ((java.util.function.Function<Object, Object>) (Data_Ring.ringFn)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictCommutativeRing_0).get("Ring0"))).apply(null /* TODO: PrimUndefined */)); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("Ring0", (java.util.function.Function<Object, Object>) (_dollar__unused_2) -> ringFn_1); }}; } })).get();
}
