public class Data_Decidable {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object identity = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object lose = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("lose");
public static final Object lost = (java.util.function.Function<Object, Object>) (dictDecidable_0) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictDecidable_0).get("lose"))).apply(Data_Decidable.identity);
public static final Object decidablePredicate = new java.util.LinkedHashMap<String, Object>() {{ put("lose", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (a_1) -> ((new java.util.function.Supplier<Object>() { Object spin_2 = (java.util.function.Function<Object, Object>) (v_3) -> ((java.util.function.Supplier<Object>) () -> { Object __tco_v_3 = v_3; while(true) { final Object __final_v_3 = __tco_v_3; try { return ((java.util.function.Supplier<Object>) () -> { throw new TcoLoop("spin_2", new Object[]{__final_v_3}); }).get(); } catch (TcoLoop __tco_ex) { __tco_v_3 = __tco_ex.args[0]; } } }).get(); public Object get() { return ((java.util.function.Function<Object, Object>) (spin_2)).apply(((java.util.function.Function<Object, Object>) (f_0)).apply(a_1)); } })).get()); put("Decide0", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Data_Decide.choosePredicate); put("Divisible1", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Data_Divisible.divisiblePredicate); }};
public static final Object decidableOp = (java.util.function.Function<Object, Object>) (dictMonoid_0) -> ((new java.util.function.Supplier<Object>() { Object chooseOp_1 = ((java.util.function.Function<Object, Object>) (Data_Decide.chooseOp)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonoid_0).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */)); public Object get() { return ((new java.util.function.Supplier<Object>() { Object divisibleOp_2 = ((java.util.function.Function<Object, Object>) (Data_Divisible.divisibleOp)).apply(dictMonoid_0); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("lose", (java.util.function.Function<Object, Object>) (f_3) -> (java.util.function.Function<Object, Object>) (a_4) -> ((new java.util.function.Supplier<Object>() { Object spin_5 = (java.util.function.Function<Object, Object>) (v_6) -> ((java.util.function.Supplier<Object>) () -> { Object __tco_v_6 = v_6; while(true) { final Object __final_v_6 = __tco_v_6; try { return ((java.util.function.Supplier<Object>) () -> { throw new TcoLoop("spin_5", new Object[]{__final_v_6}); }).get(); } catch (TcoLoop __tco_ex) { __tco_v_6 = __tco_ex.args[0]; } } }).get(); public Object get() { return ((java.util.function.Function<Object, Object>) (spin_5)).apply(((java.util.function.Function<Object, Object>) (f_3)).apply(a_4)); } })).get()); put("Decide0", (java.util.function.Function<Object, Object>) (_dollar__unused_3) -> chooseOp_1); put("Divisible1", (java.util.function.Function<Object, Object>) (_dollar__unused_3) -> divisibleOp_2); }}; } })).get(); } })).get();
public static final Object decidableEquivalence = new java.util.LinkedHashMap<String, Object>() {{ put("lose", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (a_1) -> ((new java.util.function.Supplier<Object>() { Object spin_2 = (java.util.function.Function<Object, Object>) (v_3) -> ((java.util.function.Supplier<Object>) () -> { Object __tco_v_3 = v_3; while(true) { final Object __final_v_3 = __tco_v_3; try { return ((java.util.function.Supplier<Object>) () -> { throw new TcoLoop("spin_2", new Object[]{__final_v_3}); }).get(); } catch (TcoLoop __tco_ex) { __tco_v_3 = __tco_ex.args[0]; } } }).get(); public Object get() { return ((java.util.function.Function<Object, Object>) (spin_2)).apply(((java.util.function.Function<Object, Object>) (f_0)).apply(a_1)); } })).get()); put("Decide0", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Data_Decide.chooseEquivalence); put("Divisible1", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Data_Divisible.divisibleEquivalence); }};
public static final Object decidableComparison = new java.util.LinkedHashMap<String, Object>() {{ put("lose", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (a_1) -> (java.util.function.Function<Object, Object>) (v_2) -> ((new java.util.function.Supplier<Object>() { Object spin_3 = (java.util.function.Function<Object, Object>) (v_4) -> ((java.util.function.Supplier<Object>) () -> { Object __tco_v_4 = v_4; while(true) { final Object __final_v_4 = __tco_v_4; try { return ((java.util.function.Supplier<Object>) () -> { throw new TcoLoop("spin_3", new Object[]{__final_v_4}); }).get(); } catch (TcoLoop __tco_ex) { __tco_v_4 = __tco_ex.args[0]; } } }).get(); public Object get() { return ((java.util.function.Function<Object, Object>) (spin_3)).apply(((java.util.function.Function<Object, Object>) (f_0)).apply(a_1)); } })).get()); put("Decide0", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Data_Decide.chooseComparison); put("Divisible1", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Data_Divisible.divisibleComparison); }};
}
