public class Effect_Uncurried {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };
    public static Object mkEffectFn1 = FFI_STUB;
    public static Object mkEffectFn10 = FFI_STUB;
    public static Object mkEffectFn2 = FFI_STUB;
    public static Object mkEffectFn3 = FFI_STUB;
    public static Object mkEffectFn4 = FFI_STUB;
    public static Object mkEffectFn5 = FFI_STUB;
    public static Object mkEffectFn6 = FFI_STUB;
    public static Object mkEffectFn7 = FFI_STUB;
    public static Object mkEffectFn8 = FFI_STUB;
    public static Object mkEffectFn9 = FFI_STUB;
    public static Object runEffectFn1 = FFI_STUB;
    public static Object runEffectFn10 = FFI_STUB;
    public static Object runEffectFn2 = FFI_STUB;
    public static Object runEffectFn3 = FFI_STUB;
    public static Object runEffectFn4 = FFI_STUB;
    public static Object runEffectFn5 = FFI_STUB;
    public static Object runEffectFn6 = FFI_STUB;
    public static Object runEffectFn7 = FFI_STUB;
    public static Object runEffectFn8 = FFI_STUB;
    public static Object runEffectFn9 = FFI_STUB;

public static final Object semigroupEffectFn9 = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (f1_1) -> (java.util.function.Function<Object, Object>) (f2_2) -> (java.util.function.Function<Object, Object>) (a_3) -> (java.util.function.Function<Object, Object>) (__local_var_4) -> (java.util.function.Function<Object, Object>) (c_5) -> (java.util.function.Function<Object, Object>) (__local_var_6) -> (java.util.function.Function<Object, Object>) (e_7) -> (java.util.function.Function<Object, Object>) (__local_var_8) -> (java.util.function.Function<Object, Object>) (g_9) -> (java.util.function.Function<Object, Object>) (__local_var_10) -> (java.util.function.Function<Object, Object>) (i_11) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Effect.lift2)).apply(((java.util.LinkedHashMap<String, Object>) dictSemigroup_0).get("append")))).apply(null /* TODO: UncurriedEffectApp */))).apply(null /* TODO: UncurriedEffectApp */)); }};
public static final Object semigroupEffectFn8 = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (f1_1) -> (java.util.function.Function<Object, Object>) (f2_2) -> (java.util.function.Function<Object, Object>) (a_3) -> (java.util.function.Function<Object, Object>) (__local_var_4) -> (java.util.function.Function<Object, Object>) (c_5) -> (java.util.function.Function<Object, Object>) (__local_var_6) -> (java.util.function.Function<Object, Object>) (e_7) -> (java.util.function.Function<Object, Object>) (__local_var_8) -> (java.util.function.Function<Object, Object>) (g_9) -> (java.util.function.Function<Object, Object>) (__local_var_10) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Effect.lift2)).apply(((java.util.LinkedHashMap<String, Object>) dictSemigroup_0).get("append")))).apply(null /* TODO: UncurriedEffectApp */))).apply(null /* TODO: UncurriedEffectApp */)); }};
public static final Object semigroupEffectFn7 = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (f1_1) -> (java.util.function.Function<Object, Object>) (f2_2) -> (java.util.function.Function<Object, Object>) (a_3) -> (java.util.function.Function<Object, Object>) (__local_var_4) -> (java.util.function.Function<Object, Object>) (c_5) -> (java.util.function.Function<Object, Object>) (__local_var_6) -> (java.util.function.Function<Object, Object>) (e_7) -> (java.util.function.Function<Object, Object>) (__local_var_8) -> (java.util.function.Function<Object, Object>) (g_9) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Effect.lift2)).apply(((java.util.LinkedHashMap<String, Object>) dictSemigroup_0).get("append")))).apply(null /* TODO: UncurriedEffectApp */))).apply(null /* TODO: UncurriedEffectApp */)); }};
public static final Object semigroupEffectFn6 = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (f1_1) -> (java.util.function.Function<Object, Object>) (f2_2) -> (java.util.function.Function<Object, Object>) (a_3) -> (java.util.function.Function<Object, Object>) (__local_var_4) -> (java.util.function.Function<Object, Object>) (c_5) -> (java.util.function.Function<Object, Object>) (__local_var_6) -> (java.util.function.Function<Object, Object>) (e_7) -> (java.util.function.Function<Object, Object>) (__local_var_8) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Effect.lift2)).apply(((java.util.LinkedHashMap<String, Object>) dictSemigroup_0).get("append")))).apply(null /* TODO: UncurriedEffectApp */))).apply(null /* TODO: UncurriedEffectApp */)); }};
public static final Object semigroupEffectFn5 = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (f1_1) -> (java.util.function.Function<Object, Object>) (f2_2) -> (java.util.function.Function<Object, Object>) (a_3) -> (java.util.function.Function<Object, Object>) (__local_var_4) -> (java.util.function.Function<Object, Object>) (c_5) -> (java.util.function.Function<Object, Object>) (__local_var_6) -> (java.util.function.Function<Object, Object>) (e_7) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Effect.lift2)).apply(((java.util.LinkedHashMap<String, Object>) dictSemigroup_0).get("append")))).apply(null /* TODO: UncurriedEffectApp */))).apply(null /* TODO: UncurriedEffectApp */)); }};
public static final Object semigroupEffectFn4 = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (f1_1) -> (java.util.function.Function<Object, Object>) (f2_2) -> (java.util.function.Function<Object, Object>) (a_3) -> (java.util.function.Function<Object, Object>) (__local_var_4) -> (java.util.function.Function<Object, Object>) (c_5) -> (java.util.function.Function<Object, Object>) (__local_var_6) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Effect.lift2)).apply(((java.util.LinkedHashMap<String, Object>) dictSemigroup_0).get("append")))).apply(null /* TODO: UncurriedEffectApp */))).apply(null /* TODO: UncurriedEffectApp */)); }};
public static final Object semigroupEffectFn3 = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (f1_1) -> (java.util.function.Function<Object, Object>) (f2_2) -> (java.util.function.Function<Object, Object>) (a_3) -> (java.util.function.Function<Object, Object>) (__local_var_4) -> (java.util.function.Function<Object, Object>) (c_5) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Effect.lift2)).apply(((java.util.LinkedHashMap<String, Object>) dictSemigroup_0).get("append")))).apply(null /* TODO: UncurriedEffectApp */))).apply(null /* TODO: UncurriedEffectApp */)); }};
public static final Object semigroupEffectFn2 = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (f1_1) -> (java.util.function.Function<Object, Object>) (f2_2) -> (java.util.function.Function<Object, Object>) (a_3) -> (java.util.function.Function<Object, Object>) (__local_var_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Effect.lift2)).apply(((java.util.LinkedHashMap<String, Object>) dictSemigroup_0).get("append")))).apply(null /* TODO: UncurriedEffectApp */))).apply(null /* TODO: UncurriedEffectApp */)); }};
public static final Object semigroupEffectFn10 = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (f1_1) -> (java.util.function.Function<Object, Object>) (f2_2) -> (java.util.function.Function<Object, Object>) (a_3) -> (java.util.function.Function<Object, Object>) (__local_var_4) -> (java.util.function.Function<Object, Object>) (c_5) -> (java.util.function.Function<Object, Object>) (__local_var_6) -> (java.util.function.Function<Object, Object>) (e_7) -> (java.util.function.Function<Object, Object>) (__local_var_8) -> (java.util.function.Function<Object, Object>) (g_9) -> (java.util.function.Function<Object, Object>) (__local_var_10) -> (java.util.function.Function<Object, Object>) (i_11) -> (java.util.function.Function<Object, Object>) (__local_var_12) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Effect.lift2)).apply(((java.util.LinkedHashMap<String, Object>) dictSemigroup_0).get("append")))).apply(null /* TODO: UncurriedEffectApp */))).apply(null /* TODO: UncurriedEffectApp */)); }};
public static final Object semigroupEffectFn1 = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (f1_1) -> (java.util.function.Function<Object, Object>) (f2_2) -> (java.util.function.Function<Object, Object>) (a_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Effect.lift2)).apply(((java.util.LinkedHashMap<String, Object>) dictSemigroup_0).get("append")))).apply(null /* TODO: UncurriedEffectApp */))).apply(null /* TODO: UncurriedEffectApp */)); }};
public static final Object monoidEffectFn9 = (java.util.function.Function<Object, Object>) (dictMonoid_0) -> ((new java.util.function.Supplier<Object>() { Object mempty_1 = ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (Effect.monoidEffect)).apply(dictMonoid_0)).get("mempty"); public Object get() { return ((new java.util.function.Supplier<Object>() { Object semigroupEffectFn91_2 = ((java.util.function.Function<Object, Object>) (Effect_Uncurried.semigroupEffectFn9)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonoid_0).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */)); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("mempty", (java.util.function.Function<Object, Object>) (v_3) -> (java.util.function.Function<Object, Object>) (__local_var_4) -> (java.util.function.Function<Object, Object>) (v2_5) -> (java.util.function.Function<Object, Object>) (__local_var_6) -> (java.util.function.Function<Object, Object>) (v4_7) -> (java.util.function.Function<Object, Object>) (__local_var_8) -> (java.util.function.Function<Object, Object>) (v6_9) -> (java.util.function.Function<Object, Object>) (__local_var_10) -> (java.util.function.Function<Object, Object>) (v8_11) -> mempty_1); put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar__unused_3) -> semigroupEffectFn91_2); }}; } })).get(); } })).get();
public static final Object monoidEffectFn8 = (java.util.function.Function<Object, Object>) (dictMonoid_0) -> ((new java.util.function.Supplier<Object>() { Object mempty_1 = ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (Effect.monoidEffect)).apply(dictMonoid_0)).get("mempty"); public Object get() { return ((new java.util.function.Supplier<Object>() { Object semigroupEffectFn81_2 = ((java.util.function.Function<Object, Object>) (Effect_Uncurried.semigroupEffectFn8)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonoid_0).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */)); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("mempty", (java.util.function.Function<Object, Object>) (v_3) -> (java.util.function.Function<Object, Object>) (__local_var_4) -> (java.util.function.Function<Object, Object>) (v2_5) -> (java.util.function.Function<Object, Object>) (__local_var_6) -> (java.util.function.Function<Object, Object>) (v4_7) -> (java.util.function.Function<Object, Object>) (__local_var_8) -> (java.util.function.Function<Object, Object>) (v6_9) -> (java.util.function.Function<Object, Object>) (__local_var_10) -> mempty_1); put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar__unused_3) -> semigroupEffectFn81_2); }}; } })).get(); } })).get();
public static final Object monoidEffectFn7 = (java.util.function.Function<Object, Object>) (dictMonoid_0) -> ((new java.util.function.Supplier<Object>() { Object mempty_1 = ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (Effect.monoidEffect)).apply(dictMonoid_0)).get("mempty"); public Object get() { return ((new java.util.function.Supplier<Object>() { Object semigroupEffectFn71_2 = ((java.util.function.Function<Object, Object>) (Effect_Uncurried.semigroupEffectFn7)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonoid_0).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */)); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("mempty", (java.util.function.Function<Object, Object>) (v_3) -> (java.util.function.Function<Object, Object>) (__local_var_4) -> (java.util.function.Function<Object, Object>) (v2_5) -> (java.util.function.Function<Object, Object>) (__local_var_6) -> (java.util.function.Function<Object, Object>) (v4_7) -> (java.util.function.Function<Object, Object>) (__local_var_8) -> (java.util.function.Function<Object, Object>) (v6_9) -> mempty_1); put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar__unused_3) -> semigroupEffectFn71_2); }}; } })).get(); } })).get();
public static final Object monoidEffectFn6 = (java.util.function.Function<Object, Object>) (dictMonoid_0) -> ((new java.util.function.Supplier<Object>() { Object mempty_1 = ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (Effect.monoidEffect)).apply(dictMonoid_0)).get("mempty"); public Object get() { return ((new java.util.function.Supplier<Object>() { Object semigroupEffectFn61_2 = ((java.util.function.Function<Object, Object>) (Effect_Uncurried.semigroupEffectFn6)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonoid_0).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */)); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("mempty", (java.util.function.Function<Object, Object>) (v_3) -> (java.util.function.Function<Object, Object>) (__local_var_4) -> (java.util.function.Function<Object, Object>) (v2_5) -> (java.util.function.Function<Object, Object>) (__local_var_6) -> (java.util.function.Function<Object, Object>) (v4_7) -> (java.util.function.Function<Object, Object>) (__local_var_8) -> mempty_1); put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar__unused_3) -> semigroupEffectFn61_2); }}; } })).get(); } })).get();
public static final Object monoidEffectFn5 = (java.util.function.Function<Object, Object>) (dictMonoid_0) -> ((new java.util.function.Supplier<Object>() { Object mempty_1 = ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (Effect.monoidEffect)).apply(dictMonoid_0)).get("mempty"); public Object get() { return ((new java.util.function.Supplier<Object>() { Object semigroupEffectFn51_2 = ((java.util.function.Function<Object, Object>) (Effect_Uncurried.semigroupEffectFn5)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonoid_0).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */)); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("mempty", (java.util.function.Function<Object, Object>) (v_3) -> (java.util.function.Function<Object, Object>) (__local_var_4) -> (java.util.function.Function<Object, Object>) (v2_5) -> (java.util.function.Function<Object, Object>) (__local_var_6) -> (java.util.function.Function<Object, Object>) (v4_7) -> mempty_1); put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar__unused_3) -> semigroupEffectFn51_2); }}; } })).get(); } })).get();
public static final Object monoidEffectFn4 = (java.util.function.Function<Object, Object>) (dictMonoid_0) -> ((new java.util.function.Supplier<Object>() { Object mempty_1 = ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (Effect.monoidEffect)).apply(dictMonoid_0)).get("mempty"); public Object get() { return ((new java.util.function.Supplier<Object>() { Object semigroupEffectFn41_2 = ((java.util.function.Function<Object, Object>) (Effect_Uncurried.semigroupEffectFn4)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonoid_0).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */)); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("mempty", (java.util.function.Function<Object, Object>) (v_3) -> (java.util.function.Function<Object, Object>) (__local_var_4) -> (java.util.function.Function<Object, Object>) (v2_5) -> (java.util.function.Function<Object, Object>) (__local_var_6) -> mempty_1); put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar__unused_3) -> semigroupEffectFn41_2); }}; } })).get(); } })).get();
public static final Object monoidEffectFn3 = (java.util.function.Function<Object, Object>) (dictMonoid_0) -> ((new java.util.function.Supplier<Object>() { Object mempty_1 = ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (Effect.monoidEffect)).apply(dictMonoid_0)).get("mempty"); public Object get() { return ((new java.util.function.Supplier<Object>() { Object semigroupEffectFn31_2 = ((java.util.function.Function<Object, Object>) (Effect_Uncurried.semigroupEffectFn3)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonoid_0).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */)); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("mempty", (java.util.function.Function<Object, Object>) (v_3) -> (java.util.function.Function<Object, Object>) (__local_var_4) -> (java.util.function.Function<Object, Object>) (v2_5) -> mempty_1); put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar__unused_3) -> semigroupEffectFn31_2); }}; } })).get(); } })).get();
public static final Object monoidEffectFn2 = (java.util.function.Function<Object, Object>) (dictMonoid_0) -> ((new java.util.function.Supplier<Object>() { Object mempty_1 = ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (Effect.monoidEffect)).apply(dictMonoid_0)).get("mempty"); public Object get() { return ((new java.util.function.Supplier<Object>() { Object semigroupEffectFn21_2 = ((java.util.function.Function<Object, Object>) (Effect_Uncurried.semigroupEffectFn2)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonoid_0).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */)); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("mempty", (java.util.function.Function<Object, Object>) (v_3) -> (java.util.function.Function<Object, Object>) (__local_var_4) -> mempty_1); put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar__unused_3) -> semigroupEffectFn21_2); }}; } })).get(); } })).get();
public static final Object monoidEffectFn10 = (java.util.function.Function<Object, Object>) (dictMonoid_0) -> ((new java.util.function.Supplier<Object>() { Object mempty_1 = ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (Effect.monoidEffect)).apply(dictMonoid_0)).get("mempty"); public Object get() { return ((new java.util.function.Supplier<Object>() { Object semigroupEffectFn101_2 = ((java.util.function.Function<Object, Object>) (Effect_Uncurried.semigroupEffectFn10)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonoid_0).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */)); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("mempty", (java.util.function.Function<Object, Object>) (v_3) -> (java.util.function.Function<Object, Object>) (__local_var_4) -> (java.util.function.Function<Object, Object>) (v2_5) -> (java.util.function.Function<Object, Object>) (__local_var_6) -> (java.util.function.Function<Object, Object>) (v4_7) -> (java.util.function.Function<Object, Object>) (__local_var_8) -> (java.util.function.Function<Object, Object>) (v6_9) -> (java.util.function.Function<Object, Object>) (__local_var_10) -> (java.util.function.Function<Object, Object>) (v8_11) -> (java.util.function.Function<Object, Object>) (__local_var_12) -> mempty_1); put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar__unused_3) -> semigroupEffectFn101_2); }}; } })).get(); } })).get();
public static final Object monoidEffectFn1 = (java.util.function.Function<Object, Object>) (dictMonoid_0) -> ((new java.util.function.Supplier<Object>() { Object mempty_1 = ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (Effect.monoidEffect)).apply(dictMonoid_0)).get("mempty"); public Object get() { return ((new java.util.function.Supplier<Object>() { Object semigroupEffectFn11_2 = ((java.util.function.Function<Object, Object>) (Effect_Uncurried.semigroupEffectFn1)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonoid_0).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */)); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("mempty", (java.util.function.Function<Object, Object>) (v_3) -> mempty_1); put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar__unused_3) -> semigroupEffectFn11_2); }}; } })).get(); } })).get();
}
