public class Effect {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };
    public static Object bindE = FFI_STUB;
    public static Object forE = FFI_STUB;
    public static Object foreachE = FFI_STUB;
    public static Object pureE = FFI_STUB;
    public static Object untilE = FFI_STUB;
    public static Object whileE = FFI_STUB;

public static final Object monadEffect = new java.util.LinkedHashMap<String, Object>() {{ put("Applicative0", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Effect.applicativeEffect); put("Bind1", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Effect.bindEffect); }};
public static final Object bindEffect = new java.util.LinkedHashMap<String, Object>() {{ put("bind", (java.util.function.Function<Object, Object>) (a) -> (java.util.function.Function<Object, Object>) (f) -> (java.util.function.Supplier<Object>) () -> { return ((java.util.function.Supplier<Object>) ((java.util.function.Function<Object, Object>) f).apply(((java.util.function.Supplier<Object>) a).get())).get(); }); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Effect.applyEffect); }};
public static final Object applyEffect = new java.util.LinkedHashMap<String, Object>() {{ put("apply", ((new java.util.function.Supplier<Object>() { Object __local_var_0 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Effect.monadEffect).get("Bind1"))).apply(null /* TODO: PrimUndefined */); public Object get() { return (java.util.function.Function<Object, Object>) (f_1) -> (java.util.function.Function<Object, Object>) (a_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_0).get("bind"))).apply(f_1))).apply((java.util.function.Function<Object, Object>) (f_prime_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_0).get("bind"))).apply(a_2))).apply((java.util.function.Function<Object, Object>) (a_prime_4) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Effect.monadEffect).get("Applicative0"))).apply(null /* TODO: PrimUndefined */)).get("pure"))).apply(((java.util.function.Function<Object, Object>) (f_prime_3)).apply(a_prime_4)))); } })).get()); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Effect.functorEffect); }};
public static final Object applicativeEffect = new java.util.LinkedHashMap<String, Object>() {{ put("pure", (java.util.function.Function<Object, Object>) (a) -> (java.util.function.Supplier<Object>) () -> a); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar__unused_0) -> Effect.applyEffect); }};
public static final Object functorEffect = new java.util.LinkedHashMap<String, Object>() {{ put("map", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (a_1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Effect.applicativeEffect).get("Apply0"))).apply(null /* TODO: PrimUndefined */)).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Effect.applicativeEffect).get("pure"))).apply(f_0)))).apply(a_1)); }};
public static final Object lift2 = (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (a_1) -> (java.util.function.Function<Object, Object>) (b_2) -> ((new java.util.function.Supplier<Object>() { Object __local_var_3 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Effect.monadEffect).get("Bind1"))).apply(null /* TODO: PrimUndefined */); public Object get() { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_3).get("bind"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Effect.applyEffect).get("Functor0"))).apply(null /* TODO: PrimUndefined */)).get("map"))).apply(f_0))).apply(a_1)))).apply((java.util.function.Function<Object, Object>) (f_prime_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_3).get("bind"))).apply(b_2))).apply((java.util.function.Function<Object, Object>) (a_prime_5) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Effect.monadEffect).get("Applicative0"))).apply(null /* TODO: PrimUndefined */)).get("pure"))).apply(((java.util.function.Function<Object, Object>) (f_prime_4)).apply(a_prime_5)))); } })).get();
public static final Object semigroupEffect = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("append", ((java.util.function.Function<Object, Object>) (Effect.lift2)).apply(((java.util.LinkedHashMap<String, Object>) dictSemigroup_0).get("append"))); }};
public static final Object monoidEffect = (java.util.function.Function<Object, Object>) (dictMonoid_0) -> ((new java.util.function.Supplier<Object>() { Object semigroupEffect1_1 = new java.util.LinkedHashMap<String, Object>() {{ put("append", ((java.util.function.Function<Object, Object>) (Effect.lift2)).apply(((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonoid_0).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */)).get("append"))); }}; public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("mempty", ((new java.util.function.Supplier<Object>() { Object __local_var_2 = ((java.util.LinkedHashMap<String, Object>) dictMonoid_0).get("mempty"); public Object get() { return __local_var_2; } })).get()); put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar__unused_2) -> semigroupEffect1_1); }}; } })).get();
}
