public class Test_Data_Array_ST_Partial {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object discard1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Control_Bind.discardUnit).get("discard"))).apply(Effect.bindEffect);
public static final Object peek = ((java.util.function.Function<Object, Object>) (Control_Monad_ST_Uncurried.runSTFn2)).apply(Data_Array_ST_Partial.peekImpl);
public static final Object eq1 = ((java.util.function.Function<Object, Object>) (Data_Eq.eqArrayImpl)).apply(Data_Eq.eqIntImpl);
public static final Object discard2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Control_Bind.discardUnit).get("discard"))).apply(Control_Monad_ST_Internal.bindST);
public static final Object poke = ((java.util.function.Function<Object, Object>) (Control_Monad_ST_Uncurried.runSTFn3)).apply(Data_Array_ST_Partial.pokeImpl);
public static final Object testArraySTPartial = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_Data_Array_ST_Partial.discard1)).apply(((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("peekSTArray should return the value at the specified index")))).apply((java.util.function.Function<Object, Object>) (_dollar__unused_0) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_Data_Array_ST_Partial.discard1)).apply(((java.util.function.Function<Object, Object>) (Test_Assert.$assert)).apply((((Integer) (2)) == ((Integer) (((java.util.function.Function<Object, Object>) (Control_Monad_ST_Internal.run)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Control_Monad_ST_Internal.bindST).get("bind"))).apply(null /* TODO: UncurriedEffectApp */))).apply((java.util.function.Function<Object, Object>) (a_1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_Data_Array_ST_Partial.peek)).apply(1))).apply(a_1)))))))))).apply((java.util.function.Function<Object, Object>) (_dollar__unused_1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_Data_Array_ST_Partial.discard1)).apply(((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("pokeSTArray should modify the value at the specified index")))).apply((java.util.function.Function<Object, Object>) (_dollar__unused_2) -> ((java.util.function.Function<Object, Object>) (Test_Assert.$assert)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_Data_Array_ST_Partial.eq1)).apply(null /* TODO: other literals */))).apply(((java.util.function.Function<Object, Object>) (Control_Monad_ST_Internal.run)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Control_Monad_ST_Internal.bindST).get("bind"))).apply(null /* TODO: UncurriedEffectApp */))).apply((java.util.function.Function<Object, Object>) (a_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_Data_Array_ST_Partial.discard2)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_Data_Array_ST_Partial.poke)).apply(1))).apply(4))).apply(a_3)))).apply((java.util.function.Function<Object, Object>) (_dollar__unused_4) -> null /* TODO: UncurriedEffectApp */))))))));
}
